name: Deploy prod site on push

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy Angular App
    runs-on: ubuntu-latest

    env:
      SERVER: waws-prod-ln1-025.ftp.azurewebsites.windows.net

    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2

      - name: Use Node.js 14 LTS
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install NPM Modules
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: timhomesm.homepc.it
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          port: 21
          local-dir: ./dist/
          server-dir: ./FERememberVR8/
          dangerous-clean-slate: true
